name: ci

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:

jobs:
  flatpak:
    name: "Flatpak (${{ matrix.arch }})"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install docker
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz --output ./docker.tgz
          tar xzvf docker.tgz
          mv docker/* /usr/bin
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.flatpak_minimal.flatpak_dart.example.flutter_remote_manager-${{ matrix.arch }}.flatpak
          manifest-path: org.flatpak_minimal.flatpak_dart.example.flutter_remote_manager.yml
          cache-key: flatpak-builder-${{ matrix.arch }}-${{ github.sha }}
          arch: ${{ matrix.arch }}

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-${{ matrix.arch }}
          path: org.flatpak_minimal.flatpak_dart.example.flutter_remote_manager-${{ matrix.arch }}.flatpak

      - name: Deploy to flat-manager
        continue-on-error: true
        uses: flatpak/flatpak-github-actions/flat-manager@v6
        with:
          repository: ${{ vars.FLAT_MANAGER_REPOSITORY }}
          flat-manager-url: ${{ secrets.FLAT_MANAGER_URL }}
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}

  release:
    needs: flatpak
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: flatpak-*
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            flatpak-x86_64/*.flatpak \
            flatpak-aarch64/*.flatpak \
            --generate-notes
